import Head from "next/head"

import Link from "next/link"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Night Call Scholar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tnclogo1.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <Link href="http://localhost/TNC_ARENA/TNC%20ARENA/">
            <a>The Night Call!</a>
          </Link>
        </h1>

        <p className={styles.description}>
          Parcourez nos différentes application faites avec{" "}
          <code className={styles.code}>ReactJs / NextJs</code>
        </p>

        <div className={styles.grid}>
          <Link href="">
            <a href="" className={styles.card1}>
              <h2 className="font-bold text-lg">Clicker ( building ) &rarr;</h2>

              <p>
                Recrutez les membres de The Night Call dans ce Clicker Game.
              </p>
            </a>
          </Link>

          <Link href="/Formulaire/pokemonPage">
            <a href="" className={styles.card2}>
              <h2 className="font-bold text-lg">Pokédex ( building ) &rarr;</h2>
              <p>Recherchez le pokemon pour obtenir ses informations.</p>
            </a>
          </Link>

          <Link href="/Comptable/comptablePage">
            <a href="" className={styles.card3}>
              <h2 className="font-bold text-lg">
                Comptable ( building ) &rarr;
              </h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </Link>
          <Link href="./addThings">
            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card4}
            >
              <h2 className="font-bold text-lg">➡Annuaire & co⬅ </h2>
              <p>
                Parcourez notre annuaire remplie de surprise et ajoutez vos
                envies
              </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="http://localhost/TNC_ARENA/TNC%20ARENA/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image
              src="/tnclogo1.png"
              alt="Vercel Logo"
              width={150}
              height={90}
            />
          </span>
        </a> */}
      </footer>
    </div>
  )
}
